import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import './globals.css'
import {Navbar} from "@/component/header/Navbar";
import {Footer} from "@/component/footer/Footer";
import React from "react";

const inter = Inter({ subsets: ['latin'] })
const poppins  = Poppins({subsets :['latin'],weight: ["400", "500", "600", "700", "800", "900"],})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <div className={'container'}>
          <Navbar/>
          {children}
          <Footer />
      </div>
      </body>
    </html>
  )
}
